title: Ben Tice
logo: /assets/img/profilephoto.jpg
description: Data Science Enthusiast
linkedin: https://www.linkedin.com/in/ben-tice/
email: bentice49@gmail.com
github: https://github.com/bentice
angellist: https://angel.co/ben-tice
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal